[build]
  functions = "netlify/functions"   # karena Base directory kamu = backend, path ini relatif ke backend

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "cors", "serverless-http"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
